### ISSUE TITLE
Comment Mail v160611-RC (Release Candidate)

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#278]
### Downloads

- [Comment Mail Lite v160611-RC](http://comment-mail.com/r/download-comment-mail-lite-v160611-rc/)
- [Comment Mail Pro v160611-RC](https://comment-mail.com/r/download-comment-mail-pro-v160611-rc/) (requires being logged into comment-mail.com)

### Changelog

- See [Comment Mail v160611-RC Release Announcement](http://comment-mail.com/comment-mail-v160611-rc-release-candidate/)

### Reporting Issues / Feedback

Please report any issues or feedback related to this Release Candidate using this GitHub issue. Please post a comment below with details. 

If you are reporting a UI-related issue, please include a screenshot.

If you are reporting a bug, please provide list of steps to reproduce and if the bug is related to an existing GitHub issue, please provide a link to that GitHub issue as well.

---- 

## Reported Issues to Fix

- [x] The Lite version incorrectly [contains](https://github.com/websharks/comment-mail/tree/160611-RC/src/includes/templates) `src/includes/templates/type-a/*`, which should not exist as Advanced Templates are a Pro-only feature.
- [x] When Comet Cache is installed on a site, saving the Comment Mail options—e.g., changing and saving the Comment Form configuration option, which directly affects content on the front-end of the site—does not trigger an automated clearing of the cache. At first I thought this might be a Comet Cache issue, but I realized that what probably needs to happen is Comment Mail probably needs to be firing a hook that Comet Cache is already listening for, so this seems like a Comment Mail issue.
- [x] When attempting to Subscribe without Commenting in the Lite version, the SSO actions (a Pro-only feature) are loaded, which results in a fatal error. See https://github.com/websharks/comment-mail/issues/278#issuecomment-226002060.
- [x] Disabling Data Safeguards (**Comment Mail → Config. Options → Data Safeguards**) and then deactivating and deleting the plugin **does not** delete `comment_mail_options` from the database as you would expect)
- [x] When a site contains subscription data (such as the previous release of Comment Mail), the Lite version shows the Import/Export option on the left-hand side menu of the Dashboard but doesn't do anything, i.e. no instructions or UI panel to import the subscriptions. https://github.com/websharks/comment-mail/issues/278#issuecomment-225997894
- [x] Installing the Lite version on a site that doesn't contain any StCR data in the database (and doesn't even have StCR installed) still generates the Dashboard notice welcoming the site owner as a StCR user. https://github.com/websharks/comment-mail/issues/278#issuecomment-226004812
- [x] Fatal error upgrading from Comment Mail Lite v160213; see https://github.com/websharks/comment-mail/issues/278#issuecomment-226948078

**Comment by raamdev** [comment]
The Lite version incorrectly [contains](https://github.com/websharks/comment-mail/tree/160611-RC/src/includes/templates) `src/includes/templates/type-a/*`, which should not exist as Advanced Templates are a Pro-only feature.

**Comment by raamdev** [comment]
When Comet Cache is installed on a site, saving the Comment Mail options—e.g., changing and saving the Comment Form configuration option, which directly affects content on the front-end of the site—does not trigger an automated clearing of the cache. At first I thought this might be a Comet Cache issue, but I realized that what probably needs to happen is Comment Mail probably needs to be firing a hook that Comet Cache is already listening for, so this seems like a Comment Mail issue.

**Comment by kristineds** [comment]
When a site contains subscription data (such as the previous release of Comment Mail), the Lite version shows the Import/Export option on the left-hand side menu of the Dashboard but doesn't do anything, i.e. no instructions or UI panel to import the subscriptions. Referencing: http://comment-mail.com/kb-article/why-did-the-importexport-feature-disappear/

![screen shot 2016-06-15 at 3 52 33 am](https://cloud.githubusercontent.com/assets/7514953/16057555/38e0056a-32ad-11e6-9aa0-22aea7150e47.png)

**Comment by kristineds** [comment]
When Comment Form Subscr. Options Template is _enabled_ with Auto-Subscribe and Auto-Confirm _disabled_, clicking on the options **subscribe without commenting** and **manage my subscriptions**  on a post are both showing fatal errors like this:

```php
Fatal error: Uncaught Error: Class 'WebSharks\CommentMail\SsoActions' not found in /home4/wsksdev/public_html/kristine/wp-content/plugins/comment-mail/src/includes/classes/Actions.php:55 Stack trace: #0 /home4/wsksdev/public_html/kristine/wp-content/plugins/comment-mail/src/includes/classes/Actions.php(36): WebSharks\CommentMail\Actions->maybeDoSsoActions() #1 /home4/wsksdev/public_html/kristine/wp-content/plugins/comment-mail/src/includes/classes/Plugin.php(972): WebSharks\CommentMail\Actions->__construct() #2 /home4/wsksdev/public_html/kristine/wp-includes/plugin.php(525): WebSharks\CommentMail\Plugin->actions('') #3 /home4/wsksdev/public_html/kristine/wp-settings.php(393): do_action('init') #4 /home4/wsksdev/public_html/kristine/wp-config.php(83): require_once('/home4/wsksdev/...') #5 /home4/wsksdev/public_html/kristine/wp-load.php(37): require_once('/home4/wsksdev/...') #6 /home4/wsksdev/public_html/kristine/wp-blog-header.php(13): require_once('/home4/wsksdev/...') #7 /home4/wsksdev/public_html/kristine/index.php(17) in /home4/wsksdev/public_html/kristine/wp-content/plugins/comment-mail/src/includes/classes/Actions.php on line 55
```
![screen shot 2016-06-15 at 4 06 55 am](https://cloud.githubusercontent.com/assets/7514953/16058131/7af25028-32af-11e6-8225-a33865efe9fa.png)
This was tested in two situations:

- Site owner logged-in
- Visitor logged-out

**Comment by raamdev** [comment]
Disabling Data Safeguards (**Comment Mail → Config. Options → Data Safeguards**) and then deactivating and deleting the plugin **does not** delete `comment_mail_options` from the database as you would expect).

**Comment by raamdev** [comment]
Installing the Lite version on a site **that doesn't contain any StCR data in the database** (and doesn't even have StCR installed) still generates the Dashboard notice welcoming the site owner as a StCR user:

![2016-06-14_16-19-41](https://cloud.githubusercontent.com/assets/53005/16058431/72f799e0-324c-11e6-8a88-95c919acae0e.png)

**Comment by raamdev** [comment]
@kristineds writes...
> When a site contains subscription data (such as the previous release of Comment Mail), the Lite version shows the Import/Export option on the left-hand side menu of the Dashboard but doesn't do anything, i.e. no instructions or UI panel to import the subscriptions. 

@raamdev writes...
> Installing the Lite version on a site that doesn't contain any StCR data in the database (and doesn't even have StCR installed) still generates the Dashboard notice welcoming the site owner as a StCR user

As I suspected, the issue I reported was related to the issue Kristine reported.

There were a few issues here:

- When you delete the StCR plugin from your site, _the StCR plugin options are not removed from the database_. (See https://github.com/stcr/subscribe-to-comments-reloaded/issues/228.) As a result, [this Comment Mail conditional](https://github.com/websharks/comment-mail/blob/160611-RC/src/includes/functions/stcr.php#L21-L25) that checks if the `subscribe_reloaded_version` option exists was returning `true` and Comment Mail was assuming that we should proceed as if the user has StCR installed.
- The other problem was that if you had StCR installed, but you didn't have any StCR subscription data that should be imported, Comment Mail acted as if you _did_ have StCR subscription data to import and presented you with the Import/Export menu option (which showed up as blank when you load in the Lite version because the Import/Export page itself _does_ check if `ImportStcr::dataExists()`).

To fix these issues https://github.com/websharks/comment-mail-pro/commit/331a74b1c36deab19708538aaa97d6ae303e6d3e accomplishes the following:

- Hides the Import/Export menu option unless `IS_PRO || ImportStcr::dataExists()`
- Improves the "Upgrading from StCR" Dashboard message so that it doesn't show a note about importing StCR subscription data when none exists:

Without StCR subscription data to import:

![2016-06-15_21-14-20](https://cloud.githubusercontent.com/assets/53005/16102510/28e49afe-333e-11e6-831b-8e4df28a4fa9.png)

With StCR subscription data to import:

![2016-06-14_16-19-41](https://cloud.githubusercontent.com/assets/53005/16102513/2ccd0e6c-333e-11e6-9c82-b1347f17d325.png)

**Comment by Reedyseth** [comment]
@raamdev 
> When you delete the StCR plugin from your site, the StCR plugin options are not removed from the database. (See stcr/subscribe-to-comments-reloaded#228) As a result, this Comment Mail conditional that checks if the subscribe_reloaded_version option exists was returning true and Comment Mail was assuming that we should proceed as if the user has StCR installed.

Alright, copy that I will follow up the issue open on StCR as well of this :+1:

**Comment by jaswsinc** [comment]
> IS_PRO || ImportStcr::dataExists()

Ah. Great catch! :-)

**Comment by raamdev** [comment]
Fatal error upgrading from Comment Mail Lite v160213 (built from the `release/160611-RC` branch as of 2016-06-18):

```
( ! ) Fatal error: Uncaught Exception: Missing template: `type-a/site/header.php`. in /srv/www/wordpress-default/wp-content/plugins/comment-mail/src/includes/classes/Template.php on line 355
( ! ) Exception: Missing template: `type-a/site/header.php`. in /srv/www/wordpress-default/wp-content/plugins/comment-mail/src/includes/classes/Template.php on line 355
Call Stack
#	Time	Memory	Function	Location
1	0.2024	361200	{main}( )	.../index.php:0
2	0.2031	361872	require_once( '/srv/www/wordpress-default/wp-admin/admin.php' )	.../index.php:10
3	1.1135	3784200	do_action( string(10), ??? )	.../admin.php:168
4	2.0251	3911888	WebSharks\CommentMail\Plugin->checkVersion( string(0) )	.../plugin.php:525
5	2.0299	3913232	WebSharks\CommentMail\Upgrader->__construct( )	.../Plugin.php:909
6	2.0299	3913296	WebSharks\CommentMail\Upgrader->maybeUpgrade( )	.../Upgrader.php:37
7	2.0425	3915280	WebSharks\CommentMail\UpgraderVs->__construct( string(6) )	.../Upgrader.php:53
8	2.0425	3915344	WebSharks\CommentMail\UpgraderVs->runHandlers( )	.../UpgraderVs.php:39
9	2.0425	3915344	WebSharks\CommentMail\UpgraderVs->fromLteV160213( )	.../UpgraderVs.php:50
10	2.0558	3990072	WebSharks\CommentMail\Template->__construct( string(15), string(1), true )	.../UpgraderVs.php:116
11	2.0559	3990536	WebSharks\CommentMail\Template->getFileContents( )	.../Template.php:95

```

**Comment by raamdev** [comment]
Comment Mail v160618 Released:
https://comment-mail.com/comment-mail-v160618-now-available/

Thanks to all for the testing! 👍

**Comment by jaswsinc** [comment]
Woohoo!!!!!! 😀

**Comment by kristineds** [comment]
Yay! 🎉
