### ISSUE TITLE
Comment Mail v161210-RC (Release Candidate)

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#324]
### Downloads

- [Comment Mail Lite v161210-RC](https://comment-mail.com/r/download-lite-v161210-rc/)
- [Comment Mail Pro v161210-RC](https://comment-mail.com/r/download-pro-v161210-rc/) (requires being logged into comment-mail.com)

### Changelog

- See [Comment Mail v161210-RC Release Announcement](http://comment-mail.com/comment-mail-v161210-rc-release-candidate/)

### Reporting Issues / Feedback

Please report any issues or feedback related to this Release Candidate using this GitHub issue. Please post a comment below with details. 

If you are reporting a UI-related issue, please include a screenshot.

If you are reporting a bug, please provide list of steps to reproduce and if the bug is related to an existing GitHub issue, please provide a link to that GitHub issue as well.

---- 

## Reported Issues to Fix

_None at this time._

**Comment by renzms** [comment]
### Confirmed Working

- [ ] Bug Fix (Pro): Do not show SparkPost partner image when Mandrill is selected as the RVE handler. See Issue #318.
- [ ] Accessibility: This release improves screen reader accessibility by adding aria-hidden="true" to all FontAwesome icons. See Issue #304.
- [ ] Accessibility: This release improves screen reader accessibility by offering a new setting that allows a site owner to enable or disable select menu option enhancement via jQuery. Disabling select menu option enhancement has the benefit of improving accessibility for screen readers whenever accessibility is of more concern than presentation. See: WordPress Dashboard → Comment Mail → Config Options → Misc. UI-Related Settings. See also Issue #304.

### To be tested

- [ ] Bug Fix: Prevent browser autocomplete in Comment Mail options. See Issue #319.
- [ ] Bug Fix: Searching by email address alone should always narrow to the search to that specific email address and not result in any fuzzy or fulltext matching. See Issue #226.
- [ ] Bug Fix: The conflict check for 'Subscribe to Comments Reloaded' was not working in the previous release; i.e., if you attempt to activate both Comment Mail and the 'Subscribe to Comments Reloaded' plugin at the same, this should result in a Dashboard warning. Fixed in this release. See Issue #315.
- [ ] Bug Fix: Notify 'Subscribe to Comments Reloaded' users about the comment form template being disabled under certain scenarios. See Issue #314.
- [ ] Bug Fix: Do not attempt to import 'Subscribe to Comments Reloaded' (StCR) settings if StCR is no longer installed, even if old StCR options exist in the database. See Issue #294.

- [ ] Bug Fix (Pro): Conflict checks between lite and pro corrected. This was not working properly in the previous release; i.e., installing Comment Mail Pro when Comment Mail Lite is already running should result in Comment Mail Lite being deactivated automatically. See Issue #270.
- [ ] New Feature: It is now possible to manually process the outgoing mail queue. See: WordPress Dashboard → Comment Mail → Mail Queue. See also Issue #282.
- [ ] New Feature (Pro): In Comment Mail Pro it is now possible to enable/disable comment content clipping entirely; e.g., if you prefer that email notifications include the full original comment content in raw HTML instead of being clipped and displayed in the email as plain text. See: WordPress Dashboard → Comment Mail → Config. Options → Email Notification Clips. See also: Issue #281.

**Comment by jaswsinc** [comment]
> Bug Fix: Notify 'Subscribe to Comments Reloaded' users about the comment form template being disabled under certain scenarios. See Issue #314.

In order to test this item you'll need to first install StCR and then disable the checkbox before activating Comment Mail for the first time.

![2016-12-11_10-07-00](https://cloud.githubusercontent.com/assets/1563559/21082530/acdbc166-bf89-11e6-866f-692b3b34649d.png)

**Comment by renzms** [comment]
@raamdev

![screen shot 2016-12-13 at 4 42 18 pm](https://cloud.githubusercontent.com/assets/13220018/21133307/3050f41a-c153-11e6-957d-07c45f42ef82.png)

For the RVE handler Panel

The following links in the panel go to the following:

When Mandrill is chosen:

- `Please see this KB article for detailed instructions.` goes to: http://comment-mail.com/kb-article/mandrill-rve-handler/

- The 3 links in: `This is based on checks performed by Mandrill, ` goes directly to: https://mandrill.zendesk.com/hc/en-us/articles/205583207-What-is-the-format-of-inbound-email-webhooks-

When SparkPost is chosen:

- `Please see this KB article for detailed instructions.` goes to:  http://comment-mail.com/kb-article/sparkpost-rve-handler/

Should these be updated to a link to `wpsharks.com/r/[kb-article-slug]`?

**Comment by raamdev** [comment]
> Should these be updated to a link to wpsharks.com/r/[kb-article-slug]?

They should be updated to use `comment-mail.com/r/[slug]`, yes. I'll take care of that shortly. Thanks for catching those! :-)

**Comment by raamdev** [comment]
**Comment Mail v161213** has been released and includes changes from this GitHub Issue. See the [v161213 announcement](https://comment-mail.com/comment-mail-v161213-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#324)
