### ISSUE TITLE
Finalize StCR → Comment Mail Migration Process

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#80]
This GitHub Issue will be used to track any final work necessary to finalize the StCR → Comment Mail migration process. The following tasks need to be completed (this checklist will be updated if more work is discovered to be necessary):

- [x] Test StCR → Comment Mail migration process by installing Comment Mail on a site that has StCR running with lots of existing subscriptions. 
- [x] Confirm that any relevant StCR settings get imported into CM.
- [x] Confirm that Comment Mail sends new comment reply notifications when someone replies to a comment that someone subscribed to using StCR (i.e., that the imported subscriptions are working as expected).
- [x] Confirm that all relevant Dashboard notices related to StCR → Comment Mail migration are up-to-date and make sense, with links to KB Articles where relevant.
- [x] Verify that the existing StCR → Comment Mail import routines are still compatible with StCR (they were originally written and tested with an older version of StCR and some changes have been made since then--a review of the StCR changes that have occurred since that time should be completed).
- [x] Verify that it's possible to skip the StCR subscribers import process mentioned in the Dashboard message after installing Comment Mail, but choose to run the import process later (after the Dashboard message has been dismissed); i.e., I'm assuming (but need to verify) that the Import/Export tab shows the StCR import options if you skip this after first installing Comment Mail. Also, what happens after importing StCR subscribers? Does CM warn (or prevent) you in any way from attempting to import StCR subscriptions _again_?

---

## Issues to Close

- [x] ["Upgrading from StCR" Dashboard message](https://github.com/websharks/comment-mail/issues/97)
- [x] [Improve instructions for Import/Export → Subscribe to Comments Reloaded (StCR)](https://github.com/websharks/comment-mail/issues/98)
- [x] [StCR Import Bug: "All Replies" subscriptions treated as "Replies Only To Self"](https://github.com/websharks/comment-mail/issues/162)

**Comment by raamdev** [comment]
@websharks/comment-mail-team Completing work on this GitHub Issue will depend on the completion of GitHub Issues https://github.com/websharks/comment-mail/issues/44 and https://github.com/websharks/comment-mail/issues/1 (stripping the Lite version from the Pro version, so that the Lite version can be used for testing here). 

What's important is that we don't start thoroughly testing the StCR → Comment Mail migration process until we're getting closed to a release-version of Comment Mail Lite, otherwise we'll end up doing lots of testing now, and then have to re-do all that testing again later when Comment Mail is closer to release. 

We need to make sure that the migration process is fully tested using the version of Comment Mail that new users are going to see.

There are also few things that I'm sure about, as I haven't been following @jaswsinc's Comment Mail work that closely. If the following work hasn't been done, we'll need to open separate GitHub issues for each of these so that we can complete this work:

- Does Comment Mail import any StCR options?
- Does Comment Mail import any changes to StCR message template settings?
- Does Comment Mail deactivate StCR or provide any Dashboard notification indicating that StCR should be disabled if Comment Mail is running (to avoid conflicts)?

**Comment by Reedyseth** [comment]
> There are also few things that I'm sure about, as I haven't been following @jaswsinc's Comment Mail work that closely. If the following work hasn't been done, we'll need to open separate GitHub issues for each of these so that we can complete this work:

@raamdev I would also like to add an additional point. I guess Comment Mail has the migration process for an old version of StCR.

* Does Comment Mail import any StCR options, including **the latest ones**?

**Comment by raamdev** [comment]
> an old version of StCR.

@Reedyseth That's a great point. I forgot to mention that. StCR has changed a bit since the StCR import routines in Comment Mail were written, so we'll need to do a full review of this again once we have a Lite version of Comment Mail we can start testing with. I'm going to update the checklist above to mention this.

**Comment by jaswsinc** [comment]
Referencing a dump of StrCR options:

```
INSERT INTO `wp_options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES
(11630, 'subscribe_reloaded_manager_page', '/comment-subscriptions/', 'no'),
(11631, 'subscribe_reloaded_show_subscription_box', 'yes', 'no'),
(11632, 'subscribe_reloaded_checked_by_default', 'no', 'no'),
(11633, 'subscribe_reloaded_enable_advanced_subscriptions', 'no', 'no'),
(11634, 'subscribe_reloaded_default_subscription_type', '2', 'no'),
(11635, 'subscribe_reloaded_checked_by_default_value', '0', 'no'),
(11636, 'subscribe_reloaded_checkbox_inline_style', 'width:30px', 'no'),
(11637, 'subscribe_reloaded_checkbox_html', '&lt;p class=&#039;comment-form-subscriptions&#039;&gt;&lt;label for=&#039;subscribe-reloaded&#039;&gt;[checkbox_field] [checkbox_label]&lt;/label&gt;&lt;/p&gt;', 'no'),
(11638, 'subscribe_reloaded_checkbox_label', 'Notify me of followup comments via e-mail. You can also &lt;a href=&#039;[subscribe_link]&#039;&gt;subscribe&lt;/a&gt; without commenting.', 'no'),
(11639, 'subscribe_reloaded_subscribed_label', 'You are subscribed to this post. &lt;a href=&#039;[manager_link]&#039;&gt;Manage&lt;/a&gt; your subscriptions.', 'no'),
(11640, 'subscribe_reloaded_subscribed_waiting_label', 'Your subscription to this post needs to be confirmed. &lt;a href=&#039;[manager_link]&#039;&gt;Manage your subscriptions&lt;/a&gt;.', 'no'),
(11641, 'subscribe_reloaded_author_label', 'You can &lt;a href=&#039;[manager_link]&#039;&gt;manage the subscriptions&lt;/a&gt; of this post.', 'no'),
(11642, 'subscribe_reloaded_manager_page_enabled', 'yes', 'no'),
(11643, 'subscribe_reloaded_virtual_manager_page_enabled', 'yes', 'no'),
(11644, 'subscribe_reloaded_manager_page_title', 'Manage subscriptions', 'no'),
(11645, 'subscribe_reloaded_custom_header_meta', '&lt;meta name=&#039;robots&#039; content=&#039;noindex,nofollow&#039;&gt;', 'no'),
(11646, 'subscribe_reloaded_request_mgmt_link', 'To manage your subscriptions, please enter your email address here below. We will send you a message containing the link to access your personal management page.', 'no'),
(11647, 'subscribe_reloaded_request_mgmt_link_thankyou', 'Thank you for using our subscription service. Your request has been completed, and you should receive an email with the management link in a few minutes.', 'no'),
(11648, 'subscribe_reloaded_subscribe_without_commenting', 'You can follow the discussion on &lt;strong&gt;[post_title]&lt;/strong&gt; without having to leave a comment. Cool, huh? Just enter your email address in the form here below and you&#039;re all set.', 'no'),
(11649, 'subscribe_reloaded_subscription_confirmed', 'Thank you for using our subscription service. Your request has been completed. You will receive a notification email every time a new comment to this article is approved and posted by the administrator.', 'no'),
(11650, 'subscribe_reloaded_subscription_confirmed_dci', 'Thank you for using our subscription service. In order to confirm your request, please check your email for the verification message and follow the instructions.', 'no'),
(11651, 'subscribe_reloaded_author_text', 'In order to cancel or suspend one or more notifications, select the corresponding checkbox(es) and click on the button at the end of the list.', 'no'),
(11652, 'subscribe_reloaded_user_text', 'In order to cancel or suspend one or more notifications, select the corresponding checkbox(es) and click on the button at the end of the list. You are currently subscribed to:', 'no'),
(11653, 'subscribe_reloaded_from_name', 'WordPress', 'no'),
(11654, 'subscribe_reloaded_from_email', 'jason@websharks-inc.net', 'no'),
(11655, 'subscribe_reloaded_notification_subject', 'There is a new comment to [post_title]', 'no'),
(11656, 'subscribe_reloaded_notification_content', 'There is a new comment to [post_title].\nComment Link: [comment_permalink]\nAuthor: [comment_author]\nComment:\n[comment_content]\nPermalink: [post_permalink]\nManage your subscriptions: [manager_link]', 'no'),
(11657, 'subscribe_reloaded_double_check_subject', 'Please confirm your subscription to [post_title]', 'no'),
(11658, 'subscribe_reloaded_double_check_content', 'You have requested to be notified every time a new comment is added to:\n[post_permalink]\n\nPlease confirm your request by clicking on this link:\n[confirm_link]', 'no'),
(11659, 'subscribe_reloaded_management_subject', 'Manage your subscriptions on [blog_name]', 'yes'),
(11660, 'subscribe_reloaded_management_content', 'You have requested to manage your subscriptions to the articles on [blog_name]. Follow this link to access your personal page:\n[manager_link]', 'yes'),
(11661, 'subscribe_reloaded_purge_days', '30', 'no'),
(11662, 'subscribe_reloaded_enable_double_check', 'no', 'no'),
(11663, 'subscribe_reloaded_notify_authors', 'no', 'no'),
(11664, 'subscribe_reloaded_enable_html_emails', 'no', 'no'),
(11665, 'subscribe_reloaded_htmlify_message_links', 'no', 'no'),
(11666, 'subscribe_reloaded_process_trackbacks', 'no', 'no'),
(11667, 'subscribe_reloaded_enable_admin_messages', 'no', 'no'),
(11668, 'subscribe_reloaded_admin_subscribe', 'no', 'no'),
(11669, 'subscribe_reloaded_admin_bcc', 'no', 'no'),
(19108, 'subscribe_reloaded_data_sanitized', 'yes', 'yes'),
(19110, 'subscribe_reloaded_unique_key', '0099f579645224d677fc8f162ee5d06a', 'yes'),
(19111, 'subscribe_reloaded_subscriber_table', 'yes', 'yes'),
(19112, 'subscribe_reloaded_version', '150422', 'yes');
```

**Comment by Reedyseth** [comment]
> Referencing a dump of StrCR options:

Great, if you have any question with an option I would be happy to clarify it !

**Comment by Reedyseth** [comment]
> I'm going to update the checklist above to mention this.

@raamdev Thanks !

**Comment by jaswsinc** [comment]
![2015-05-29_06-37-21](https://cloud.githubusercontent.com/assets/1563559/7884885/4b9b21ac-05cd-11e5-8494-5c1d2fec0efb.png)

**Comment by Reedyseth** [comment]
Just to bring a point that I mention before. The first time that I run the importation routing the number of subscriptions did not match, so after we have the lite version ready to test I will take this task to confirm it.

**Comment by jaswsinc** [comment]
Referencing StCR transitioning helper. Needs review:
https://github.com/websharks/comment-mail/blob/000000-dev/comment-mail/includes/stcr.php

**Comment by Reedyseth** [comment]
> Referencing StCR transitioning helper. Needs review:
> https://github.com/websharks/comment-mail/blob/000000-dev/comment-mail/includes/stcr.php

@jaswsinc  Cool, I am on it, no need to wait for the Striping !

**Comment by jaswsinc** [comment]
> The first time that I run the importation routing the number of subscriptions did not match, so after we have the lite version ready to test I will take this task to confirm it.

Great! Just let me know if you have any trouble or find a bug. Thank you :-)

**Comment by jaswsinc** [comment]
> Cool, I am on it, no need to wait for the Striping !

Awesome! Thanks @Reedyseth

**Comment by jaswsinc** [comment]
> https://github.com/websharks/comment-mail/blob/000000-dev/comment-mail/includes/stcr.php

@Reedyseth Feel free to submit a pull request for any changes/improvements you'd like to make there.

**Comment by raamdev** [comment]
Adding the following todo item to the checklist above ↑:

- Verify that it's possible to skip the StCR subscribers import process mentioned in the Dashboard message after installing Comment Mail, but choose to run the import process later (after the Dashboard message has been dismissed); i.e., I'm assuming (but need to verify) that the Import/Export tab shows the StCR import options if you skip this after first installing Comment Mail. Also, what happens after importing StCR subscribers? Does CM warn (or prevent) you in any way from attempting to import StCR subscriptions _again_?

**Comment by Reedyseth** [comment]
> Feel free to submit a pull request for any changes/improvements you'd like to make there.

@jaswsinc RIght now I have a clone of the repo, what would be better, create a branch and from that branch submit the pull request or fork the repo ?

**Comment by raamdev** [comment]
> RIght now I have a clone of the repo, what would be better, create a branch and from that branch submit the pull request or fork the repo ?

You can use the clone and create a new branch called `feature/80` (we use the number of the related GitHub issue). Then you can push the `feature/80` branch and submit a Pull Request when you're ready. :-)

**Comment by jaswsinc** [comment]
:+1:

**Comment by Reedyseth** [comment]
> You can use the clone and create a new branch called feature/80 (we use the number of the related GitHub issue). Then you can push the feature/80 branch and submit a Pull Request when you're ready. :-)

Cool, Thanks you !

**Comment by jaswsinc** [comment]
> Also, what happens after importing StCR subscribers? Does CM warn (or prevent) you in any way from attempting to import StCR subscriptions again?

No warning, but if you attempt it again it simply returns `0` imported, because they were already imported. However, if you Restore Default Options, it will allow you to do it a second time. That can lead to duplicate subscriptions though, so it's just good to watch out for that.

> i.e., I'm assuming (but need to verify) that the Import/Export tab shows the StCR import options if you skip this after first installing Comment Mail.

Yes, you can always visit the Import tab, and, in addition to that notice, there is also a blinking navigation item when you visit the options page, reminding you to complete the StCR data import in case you somehow miss it.

**Comment by jaswsinc** [comment]
> StCR has changed a bit since the StCR import routines in Comment Mail were written

I read over the changelog for StCR. Has anything changed in the storage of subscribers and/or their status flags?

**Comment by raamdev** [comment]
> Has anything changed in the storage of subscribers and/or their status flags?

I don't believe so, no, but I would want Israel to confirm that, as he's worked on the past few StCR releases.

**Comment by Reedyseth** [comment]
> I read over the changelog for StCR. Has anything changed in the storage of subscribers and/or their status flags?

Nope, the flags remain the same, no changes on that part. Something that was added is a new table to store the subscribers email addresses and a unique key for that email. This is due to the security issue by google, they call it PII, but it will not affect the subscribers information on the `postmeta` table.

**Comment by jaswsinc** [comment]
> This is due to the security issue by google, they call it PII, but it will not affect the subscribers information on the postmeta table.

Copy that. I remember you mentioning this before. So the unique key is what's being stored in the database then, not the actual subscriptions. Is that right? Sorry, just making sure I understand :-)

**Comment by Reedyseth** [comment]
> So the unique key is what's being stored in the database then, not the actual subscriptions. Is that right?

Correct, what it [store](https://github.com/stcr/subscribe-to-comments-reloaded/blob/master/subscribe-to-comments-reloaded/subscribe-to-comments-reloaded.php#L421) is the email and the unique key. This does not affect the subscriptions statuses only interact with the subscriptions forms to allow them to manage the subscription.

**Comment by raamdev** [comment]
Added two new GitHub issues to the todo list above related to finalizing the StCR Migration process. ↑

**Comment by raamdev** [comment]
Completed the checklist at the top of this issue. Closing (_finally_!). :grinning:

**Comment by jaswsinc** [comment]
:+1: Yay!
